### ISSUE TITLE
mkbootfs et mkbootimg: Aucun fichier ou dossier de ce type

### ISSUE THREAD

**Issue by olivierkeke** [micgeri/zte-openc-switch-bluedroid#2]
Le script update-bootimage.sh plante avec les messages "mkbootimg: Aucun fichier ou dossier de ce type" et "mkbootfs: Aucun fichier ou dossier de ce type".
Voici le log complet :
[err.txt](https://github.com/micgeri/zte-openc-switch-bluedroid/files/70965/err.txt)

**Comment by micgeri** [comment]
Bonjour,

Je n'arrive pas à reproduire cette anomalie.
Pouvez-vous me confirmer que vous exécutez l'opération sur le fichier boot.img extrait du __pack root du ZTE Open C__ ? Aussi,  quelle distribution Linux utilisez-vous, et dans quelle version ?

J'ai fait plusieurs modifications, dont quelques-unes sur le script de modification du boot.img. Merci de récupérer la dernière version, et d'exécuter l'outil à nouveau.

Si le problème se produit toujours (ce qui ne me surprendrait pas), effectuez alors les manipulations suivantes :
```
cd /home/olivier/Développement/git/zte-openc-switch-bluedroid/update-bootimage/
rm -rf mkbootimg_tools-bootimg-openc-ok
wget -nv -O put-files-here/mkboot.zip https://github.com/xiaolu/mkbootimg_tools/archive/master.zip
```
Ré-exécutez alors le script *update-bootimage.sh*. 

Tenez-moi informé des résultats de ces opérations svp.

Cordialement,
micgeri

**Comment by olivierkeke** [comment]
Bonjour,Il s'agit bien du pack root du zte open c. J'utilise debian 8 amd64. Je ne pourrai pas tester immédiatement vos indications, je suis loin de mon pc pour les fêtes de fin d'année... Je vous tient informé dès que j'ai pu refaire le test.Cordialement,Oliviermicgeri/zte-openc-switch-bluedroid a écrit :Bonjour,

Je n'arrive pas à reproduire cette anomalie.
Pouvez-vous me confirmer que vous exécutez l'opération sur le fichier boot.img extrait du pack root du ZTE Open C ? Aussi,  quelle distribution Linux utilisez-vous, et dans quelle version ?

J'ai fait plusieurs modifications, dont quelques-unes sur le script de modification du boot.img. Merci de récupérer la dernière version, et d'exécuter l'outil à nouveau.

Si le problème se produit toujours (ce qui ne me surprendrait pas), effectuez alors les manipulations suivantes :

cd /home/olivier/Développement/git/zte-openc-switch-bluedroid/update-bootimage/
rm -rf mkbootimg_tools-bootimg-openc-ok
wget -nv -O put-files-here/mkboot.zip https://github.com/xiaolu/mkbootimg_tools/archive/master.zip


Ré-exécutez alors le script update-bootimage.sh. 

Tenez-moi informé des résultats de ces opérations svp.

Cordialement,
micgeri

—Reply to this email directly or view it on GitHub.


  
  


Envoyé depuis Firefox OS

**Comment by micgeri** [comment]
Bonjour,

Avez-vous pu résoudre votre problème ?

Cordialement,
micgeri

**Comment by olivierkeke** [comment]
Bonjour,

J'ai suivi vos indications et la même erreur se reproduit. Ça ressemble à un problème de droit non ? J'essaierai de tester le script sur une autre machine. Sur quelle distribution l'avez vous testé ?

**Comment by micgeri** [comment]
Dans le cas d'un problème de droit (supposons en écriture), le script devrait s'arrêter avec l'erreur "Merci de donner les droits en écriture au dossier de ce script".
J'ai testé les scripts sous Debian Wheezy (7.X). J'ai ajouté cette information récemment dans le fichier README.md. Pouvez-vous me dire quelle est votre distribution ?

**Comment by olivierkeke** [comment]
Ma distrib est Debian Jessie (8.X). Je peux essayer sur une Debian testing...

**Comment by micgeri** [comment]
J'ai une Debian Jessie en VM. Je viens de tester le script dessus, et il s'est exécuté sans problème.

Ça peut paraitre anodin, mais pouvez-vous essayer d'exécuter le script hors de votre dossier Développement (par exemple, mettez-le temporairement dans /home/olivier/zte-openc-switch-bluedroid).

**Comment by olivierkeke** [comment]
Bonsoir,

J'ai retesté en faisant la modif demandé, en supprimant l'accent dans le nom de dossier, en supprimant la majuscule et j'ai toujours la même erreur.
Sur mon deuxième PC en debian testing aucun problème ! Par contre je n'ai pas pu aller au bout  des indications car le site comebuy a l'air HS...

**Comment by micgeri** [comment]
Bonsoir,

Ok. C'est bizarre comme bug.
J'ai mis le script à jour par rapport au site comebuy (il va prendre le zip autre part, maintenant).

**Comment by micgeri** [comment]
Bonjour,

J'ai vu le message que tu as posté [ici](https://github.com/mozfr/buildscommunautaires/issues/4), donc je clôture ce bug.

Cordialement,
micgeri

**Comment by olivierkeke** [comment]
Bonjour,
En effet si personne d'autre n'a signalé ce bug ça doit venir de mon installation...
Merci pour le support !
Olivier
