### ISSUE TITLE
Compatibilité Open-C FR ?

### ISSUE THREAD

**Issue by nob900** [micgeri/zte-openc-switch-bluedroid#3]
Bonjour,

(crosspost, j'ai ajouté une note qui évoque ce point là : https://github.com/mozfr/buildscommunautaires/issues/4)

Le script télécharge une archive (GEN_EU_P821E10V1.0.0B10_FUS_DL.zip) depuis Comebuy. Est-ce compatible avec les versions FR de l'Open-C ?

**Comment by micgeri** [comment]
Bonjour nob900,

Oui ça l'est (j'ai un Open C FR). A vrai dire, cette archive est uniquement téléchargé pour récupérer des fichiers nécessaire au fonctionnement du Bluetooth.

**Comment by dattaz** [comment]
les fichiers utilisé dans le téléchargement sont les même sur l'open c FR
